### ISSUE TITLE
[INVESTIGATE] Parent account cannot set the proxy account’s display field

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/hybrid-custody#62]
## Description

> In contracts/HybridCustody.cdc:429-431, the setDisplay function in the proxy account resource is not callable by any functions. Consequently, the parent account cannot set the proxy account’s display field, as indicated in line 404.
We classify this issue as major because it affects the correct functioning of the system.

## Recommendation
> We recommend allowing the parent account to call the function.

**Comment by sisyphusSmiling** [comment]
This issue seems to be a misunderstanding as a parent can set a `ProxyAccount` display via `Manager.setChildDisplay()` as seen in transaction [`hybrid-custody/metadata/set_proxy_account_display.cdc`](https://github.com/onflow/hybrid-custody/blob/main/transactions/hybrid-custody/metadata/set_proxy_account_display.cdc) and validated in test case [testMetadata_ProxyAccount_Metadata](https://github.com/onflow/hybrid-custody/blob/main/test/HybridCustody_tests.cdc#L278-L291)

```cadence
// set_proxy_account_display.cdc
import "HybridCustody"
import "MetadataViews"

transaction(childAddress: Address, name: String, description: String, thumbnail: String) {
    prepare(acct: AuthAccount) {
        let m = acct.borrow<&HybridCustody.Manager>(from: HybridCustody.ManagerStoragePath)
            ?? panic("manager not found")
        
        let d = MetadataViews.Display(
            name: name,
            description: description,
            thumbnail: MetadataViews.HTTPFile(url: thumbnail)
        )

        m.setChildDisplay(child: childAddress, display: d) // Setting ProxyAccount display via Manager
    }
}
```

The `ProxyAccount.setDisplay()` method is `access(contract)` to prevent others with access to the hybrid custody account from altering a parent-defined and controlled display value.

**Comment by austinkline** [comment]
Agreed, seems like we are missing sufficient documentation to convey this

**Comment by sisyphusSmiling** [comment]
@austinkline think we're good to close this one in favor of a new documentation ticket?

**Comment by austinkline** [comment]
I think that's fine yeah, Hao on the Lilico team was saying they were not able to update a parent account's configure display for the proxy, but our tests were not able to reproduce, and I was able to do it in testnet as well.

A doc ticket SGTM
