### ISSUE TITLE
Outstanding TODO comments in codebase

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/hybrid-custody#74]
## Description

> In several instances of the codebase, many unimplemented functionalities are marked as TODO. This decreases the readability of the codebase.

## Recommendation

> We recommend implementing the required functionalities or resolving them for better code practices.

**Comment by austinkline** [comment]
Made a ticket for the last outstanding TODO after we merge #88 

https://github.com/onflow/hybrid-custody/issues/91
